# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main
- task/Dev-Ops-Pipeline

resources:
- repo: self

variables:
  tag: '$(Build.SourceVersion)'
  pythonVersion: 3.11


steps:

- task: UsePythonVersion@0
  displayName: Use Python $(pythonVersion)
  inputs:
    versionSpec: $(pythonVersion)

- task: Bash@3
  displayName: Unit Tests
  inputs:
    targetType: 'inline'
    script: |
      python -m pip install --upgrade pip
      pip install -r dashboard/requirements.txt
      python -m unittest dashboard.test
      pip install -r soil_moisture_sensor/requirements.txt
      python -m unittest soil_moisture_sensor.test

- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'docker-hub'
    repository: '$(REPOSITORY)/python-dashboard'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
    

- task: KubernetesManifest@0
  displayName: Kubernetes Deployment
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'kube-connection'
    namespace: 'default'
    manifests: 'Kubernetes/deployment.yml'
    containers: '$(REPOSITORY)/python-dashboard:latest'
    imagePullSecrets: 'docker-hub'
    rolloutStatusTimeout: '30'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'JackPlowman'
    repositoryName: 'eperegrine/ECM3440-soil-moisture'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'v1.0.0'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'