# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main
- task/Dev-Ops-Pipeline

resources:
- repo: self

variables:
  tag: '$(Build.SourceVersion)'
  pythonVersion: 3.11


steps:

- task: UsePythonVersion@0
  displayName: Use Python $(pythonVersion)
  inputs:
    versionSpec: $(pythonVersion)

- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'docker-hub'
    repository: '$(REPOSITORY)/python-dashboard'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
    

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'kube-connection'
    namespace: 'default'
    manifests: 'Kubernetes/deployment.yml'
    containers: '$(REPOSITORY)/python-dashboard:latest'
    imagePullSecrets: 'docker-hub'
    rolloutStatusTimeout: '30'