apiVersion: v1
kind: Service
metadata:
  name: python-dashboard-service
spec:
  selector:
    app: python-dashboard
  ports:
  - protocol: "TCP"
    port: 5001
    targetPort: 5001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-dashboard
spec:
  selector:
    matchLabels:
      app: python-dashboard
  replicas: 1
  template:
    metadata:
      labels:
        app: python-dashboard
    spec:
      containers:
      - name: python-dashboard
        image: jackplowman/python-dashboard:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001